export const REGIME_CREATE_REQUEST = "REGIME_CREATE_REQUEST";
export const REGIME_CREATE_SUCCESS = "REGIME_CREATE_SUCCESS";
export const REGIME_CREATE_FAILURE = "REGIME_CREATE_FAILURE";

export const REGIME_DELETE_REQUEST = "REGIME_DELETE_REQUEST";
export const REGIME_DELETE_SUCCESS = "REGIME_DELETE_SUCCESS";
export const REGIME_DELETE_FAILURE = "REGIME_DELETE_FAILURE";


export const GET_REGIME_REQUEST = "GET_REGIME_REQUEST";
export const GET_REGIME_SUCCESS = "GET_REGIME_SUCCESS";
export const GET_REGIME_FAILURE = "GET_REGIME_FAILURE";

export const GET_CURRENT_REGIME_REQUEST = "GET_CURRENT_REGIME_REQUEST";
export const GET_CURRENT_REGIME_SUCCESS = "GET_CURRENT_REGIME_SUCCESS";
export const GET_CURRENT_REGIME_FAILURE = "GET_CURRENT_REGIME_FAILURE";


export const GET_ALL_REGIMES_REQUEST = "GET_ALL_REGIMES_REQUEST";
export const GET_ALL_REGIMES_SUCCESS = "GET_ALL_REGIMES_SUCCESS";
export const GET_ALL_REGIMES_FAILURE = "GET_ALL_REGIMES_FAILURE";

